### ISSUE TITLE
Authmiddleware should return 401 if application/json requested and authSessionId is invalid

### ISSUE THREAD

**Issue by mtestrot** [d-velop/dvelop-sdk-go#12]
Currently the user agent is redirected to the Idp login page (HTML). This is correct if html is requested but not if another mediatype like application/json is requested.
In later cases the Middleware should return 401.

**Comment by weberaj** [comment]
According to this line https://github.com/d-velop/dvelop-sdk-go/blob/5346078a09b283df81a648d2211429dcfa20e6a7/idp/authmiddleware.go#L73 a redirect should not happen for `Accept: application/json`. This should be covered by this test case https://github.com/d-velop/dvelop-sdk-go/blob/5346078a09b283df81a648d2211429dcfa20e6a7/idp/authmiddleware_test.go#L672. What accept header is the user agent sending? Does it contain a `*/*`? If it does contain it, a redirect does currently happen, see https://github.com/d-velop/dvelop-sdk-go/blob/5346078a09b283df81a648d2211429dcfa20e6a7/idp/authmiddleware_test.go#L664

**Comment by mtestrot** [comment]
The reported case is a little different. The test case you mentioned covers a situation in which there is no authsessionId at all. However, the mentioned error occurs when the request contains an expired or otherwise invalid authsessionId.

**Comment by weberaj** [comment]
Okay, if I am right and it should be handled for that case https://github.com/d-velop/dvelop-sdk-go/blob/5346078a09b283df81a648d2211429dcfa20e6a7/idp/authmiddleware.go#L103  I can submit a merge request with a fix.

**Comment by mtestrot** [comment]
Great. I think this might be the correct line of code. But please write a test before changing the production code to ensure you fix the right case.

**Comment by dvelop-swil** [comment]
I´ve added a fix for this to Thomas branch, because we needed this right now: https://github.com/thomasmkt/dvelop-sdk-go/commit/21664b9fd86d5e36ba47b00e37ba18cd8e66a388
