### ISSUE TITLE
User not found IDP GetPrincipalByID Bug - Slice bounds out of range Exception

### ISSUE THREAD

**Issue by andrisro** [d-velop/dvelop-sdk-go#18]
![image](https://user-images.githubusercontent.com/22592344/71972101-4eb98980-320c-11ea-9ac9-f7545aa0ef59.png)
Codeline 189 im client.go des IDP SDKs löst eine Slice out of bounds exception aus, wenn ich über die Funktion Daten eines Nutzers auslesen möchte, den es nicht gibt.

Die Funktion hat zuvor schonmal funktioniert. 

Nach kurzer Analyse tritt folgendes auf: Das Verhalten des IDPs auf der Userroute /scim/users/asdfjasdlfq wirft nun nur noch lediglich einen 404 ohne Body content und daher ist die responseMsg leer. Dadurch wird hier der Index -1  ausgelesen, der out of bounds ist.

**Comment by mtestrot** [comment]
Fixed. Cf. https://github.com/d-velop/dvelop-sdk-go/pull/19
